# Generated by Django 5.2.15 on 2026-06-12 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('player', models.CharField(blank=True, max_length=120, verbose_name='Игрок')),
                ('chronicle', models.CharField(blank=True, max_length=120, verbose_name='Хроника')),
                ('concept', models.CharField(blank=True, max_length=200, verbose_name='Концепция')),
                ('generation', models.PositiveSmallIntegerField(default=13, verbose_name='Поколение')),
                ('sect', models.CharField(blank=True, max_length=30, verbose_name='Секта')),
                ('sire', models.CharField(blank=True, max_length=120, verbose_name='Сир')),
                ('willpower_permanent', models.PositiveSmallIntegerField(default=1, verbose_name='Сила воли (пост.)')),
                ('willpower_current', models.PositiveSmallIntegerField(default=1, verbose_name='Сила воли (тек.)')),
                ('humanity', models.PositiveSmallIntegerField(default=7, verbose_name='Человечность')),
                ('path_name', models.CharField(blank=True, max_length=120, verbose_name='Путь (если не Человечность)')),
                ('blood_pool_current', models.PositiveSmallIntegerField(default=10, verbose_name='Запас крови (тек.)')),
                ('health', models.JSONField(blank=True, default=dict, verbose_name='Здоровье')),
                ('descriptors', models.JSONField(blank=True, default=dict, verbose_name='Дескрипторы')),
                ('history', models.TextField(blank=True, verbose_name='Квента')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.clan', verbose_name='Клан')),
                ('demeanor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rules.archetype', verbose_name='Маска')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rules.gameline', verbose_name='Линейка')),
                ('nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rules.archetype', verbose_name='Натура')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='characters.character', verbose_name='Участники')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_groups', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterFlaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Заметки')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaws', to='characters.character', verbose_name='Персонаж')),
                ('flaw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rules.flaw', verbose_name='Флоу')),
            ],
            options={
                'verbose_name': 'Флоу персонажа',
                'verbose_name_plural': 'Флоу персонажа',
                'unique_together': {('character', 'flaw')},
            },
        ),
        migrations.CreateModel(
            name='CharacterMerit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Заметки')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merits', to='characters.character', verbose_name='Персонаж')),
                ('merit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rules.merit', verbose_name='Мерит')),
            ],
            options={
                'verbose_name': 'Мерит персонажа',
                'verbose_name_plural': 'Мериты персонажа',
                'unique_together': {('character', 'merit')},
            },
        ),
        migrations.CreateModel(
            name='CharacterTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='Специализация')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Заметки')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='characters.character', verbose_name='Персонаж')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rules.trait', verbose_name='Трейт')),
            ],
            options={
                'verbose_name': 'Трейт персонажа',
                'verbose_name_plural': 'Трейты персонажа',
                'unique_together': {('character', 'trait')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Цвет')),
                ('characters', models.ManyToManyField(blank=True, related_name='tags', to='characters.character', verbose_name='Персонажи')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
