# Generated by Django 5.2.15 on 2026-06-12 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен')),
                ('can_copy', models.BooleanField(default=True, verbose_name='Можно копировать')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='characters.character', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Публичная ссылка',
                'verbose_name_plural': 'Публичные ссылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
