# Generated by Django 5.2.15 on 2026-06-12 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('edition', models.CharField(default='V20', max_length=20, verbose_name='Редакция')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Линейка',
                'verbose_name_plural': 'Линейки',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('attribute', 'Атрибут'), ('talent', 'Талант'), ('skill', 'Навык'), ('knowledge', 'Знание'), ('discipline', 'Дисциплина'), ('background', 'Бэкграунд'), ('virtue', 'Добродетель')], max_length=20, verbose_name='Категория')),
                ('code', models.SlugField(verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('subgroup', models.CharField(blank=True, max_length=20, verbose_name='Подгруппа')),
                ('min_rating', models.PositiveSmallIntegerField(default=0, verbose_name='Мин. рейтинг')),
                ('max_rating', models.PositiveSmallIntegerField(default=5, verbose_name='Макс. рейтинг')),
                ('requires_specialty_at', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Специализация с')),
                ('summary', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='rules.gameline', verbose_name='Линейка')),
            ],
            options={
                'verbose_name': 'Трейт',
                'verbose_name_plural': 'Трейты',
                'ordering': ['line', 'category', 'order', 'code'],
                'unique_together': {('line', 'category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Flaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('physical', 'Физическая'), ('mental', 'Ментальная'), ('social', 'Социальная'), ('supernatural', 'Сверхъестественная')], max_length=20, verbose_name='Категория')),
                ('code', models.SlugField(verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('summary', models.TextField(blank=True, verbose_name='Описание')),
                ('bonus', models.PositiveSmallIntegerField(default=1, verbose_name='Бонус (очки)')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.gameline', verbose_name='Линейка')),
            ],
            options={
                'verbose_name': 'Флоу',
                'verbose_name_plural': 'Флоу',
                'ordering': ['line', 'category', 'code'],
                'abstract': False,
                'unique_together': {('line', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('summary', models.TextField(blank=True, verbose_name='Описание')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='rules.gameline', verbose_name='Линейка')),
            ],
            options={
                'verbose_name': 'Архетип',
                'verbose_name_plural': 'Архетипы',
                'ordering': ['line', 'code'],
                'unique_together': {('line', 'code')},
            },
        ),
        migrations.CreateModel(
            name='GenerationStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveSmallIntegerField(verbose_name='Поколение')),
                ('max_blood_pool', models.PositiveSmallIntegerField(verbose_name='Макс. запас крови')),
                ('blood_per_turn', models.PositiveSmallIntegerField(verbose_name='Крови за ход')),
                ('max_trait_rating', models.PositiveSmallIntegerField(default=5, verbose_name='Макс. рейтинг трейта')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_stats', to='rules.gameline', verbose_name='Линейка')),
            ],
            options={
                'verbose_name': 'Параметры поколения',
                'verbose_name_plural': 'Параметры поколений',
                'ordering': ['line', '-generation'],
                'unique_together': {('line', 'generation')},
            },
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('physical', 'Физическая'), ('mental', 'Ментальная'), ('social', 'Социальная'), ('supernatural', 'Сверхъестественная')], max_length=20, verbose_name='Категория')),
                ('code', models.SlugField(verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('summary', models.TextField(blank=True, verbose_name='Описание')),
                ('cost', models.PositiveSmallIntegerField(default=1, verbose_name='Стоимость (очки)')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.gameline', verbose_name='Линейка')),
            ],
            options={
                'verbose_name': 'Мерит',
                'verbose_name_plural': 'Мериты',
                'ordering': ['line', 'category', 'code'],
                'abstract': False,
                'unique_together': {('line', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('default_sect', models.CharField(blank=True, max_length=30, verbose_name='Секта по умолчанию')),
                ('weakness_summary', models.TextField(blank=True, verbose_name='Слабость')),
                ('is_bloodline', models.BooleanField(default=False, verbose_name='Блудлайн')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clans', to='rules.gameline', verbose_name='Линейка')),
                ('disciplines', models.ManyToManyField(blank=True, limit_choices_to={'category': 'discipline'}, related_name='clans', to='rules.trait', verbose_name='Клановые дисциплины')),
            ],
            options={
                'verbose_name': 'Клан',
                'verbose_name_plural': 'Кланы',
                'ordering': ['line', 'code'],
                'unique_together': {('line', 'code')},
            },
        ),
    ]
