# Generated by Django 5.2.15 on 2026-06-12 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='origin',
            field=models.CharField(choices=[('parsed', 'Спарсено'), ('verified', 'Проверено')], default='parsed', max_length=10, verbose_name='Происхождение'),
        ),
        migrations.AddField(
            model_name='archetype',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='clan',
            name='origin',
            field=models.CharField(choices=[('parsed', 'Спарсено'), ('verified', 'Проверено')], default='parsed', max_length=10, verbose_name='Происхождение'),
        ),
        migrations.AddField(
            model_name='clan',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='flaw',
            name='origin',
            field=models.CharField(choices=[('parsed', 'Спарсено'), ('verified', 'Проверено')], default='parsed', max_length=10, verbose_name='Происхождение'),
        ),
        migrations.AddField(
            model_name='flaw',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='generationstat',
            name='origin',
            field=models.CharField(choices=[('parsed', 'Спарсено'), ('verified', 'Проверено')], default='parsed', max_length=10, verbose_name='Происхождение'),
        ),
        migrations.AddField(
            model_name='generationstat',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='merit',
            name='origin',
            field=models.CharField(choices=[('parsed', 'Спарсено'), ('verified', 'Проверено')], default='parsed', max_length=10, verbose_name='Происхождение'),
        ),
        migrations.AddField(
            model_name='merit',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='trait',
            name='origin',
            field=models.CharField(choices=[('parsed', 'Спарсено'), ('verified', 'Проверено')], default='parsed', max_length=10, verbose_name='Происхождение'),
        ),
        migrations.AddField(
            model_name='trait',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Источник'),
        ),
        migrations.CreateModel(
            name='CreationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('parsed', 'Спарсено'), ('verified', 'Проверено')], default='parsed', max_length=10, verbose_name='Происхождение')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('key', models.SlugField(verbose_name='Ключ')),
                ('value', models.JSONField(verbose_name='Значение')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creation_rules', to='rules.gameline', verbose_name='Линейка')),
            ],
            options={
                'verbose_name': 'Правило создания',
                'verbose_name_plural': 'Правила создания',
                'ordering': ['line', 'key'],
                'unique_together': {('line', 'key')},
            },
        ),
    ]
